server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://pho-gt-mysql.c1qgi0ayimmy.ap-southeast-2.rds.amazonaws.com:3306/pho_1986_db?createDatabaseIfNotExist=true&useSSL=true&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
    username: ${SPRING_DATASOURCE_USERNAME:pho_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

app:
  cors:
    allowed-origins: ${CLIENT_ORIGIN:http://localhost:5173,http://localhost:3000,http://3.25.130.70,https://pho-gt.vercel.app,https://pho-gt-git-main-hieutran2901s-projects.vercel.app}
  security:
    admin-seed:
      enabled: ${ADMIN_SEED_ENABLED:false}
      phone: ${ADMIN_INIT_PHONE:}
      password: ${ADMIN_INIT_PASSWORD:}
      full-name: ${ADMIN_INIT_NAME:Quản Trị Viên 1986}
      email: ${ADMIN_INIT_EMAIL:admin@pho1986.vn}

payment:
  sepay:
    enabled: ${SEPAY_ENABLED:false}
    environment: ${SEPAY_ENV:sandbox}
    merchant-id: ${MERCHANTID:}
    secret-key: ${SEPAY_SECRETKEY:}
    ipn-secret: ${SEPAY_IPN_SECRET:}
    ipn-url: ${SEPAY_IPN_URL:https://pho-gt.vercel.app/api/v1/payments/sepay/ipn}
    success-url: ${SEPAY_SUCCESS_URL:https://pho-gt.vercel.app/api/v1/payments/sepay/return/success}
    error-url: ${SEPAY_ERROR_URL:https://pho-gt.vercel.app/api/v1/payments/sepay/return/error}
    cancel-url: ${SEPAY_CANCEL_URL:https://pho-gt.vercel.app/api/v1/payments/sepay/return/cancel}
    booking-frontend-redirect-url: ${SEPAY_BOOKING_FRONTEND_REDIRECT_URL:https://pho-gt.vercel.app/#order}
    frontend-redirect-url: ${SEPAY_FRONTEND_REDIRECT_URL:https://pho-gt.vercel.app/#order}

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET:pho-medial-assets}
    region: ${AWS_REGION:ap-southeast-1}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
