server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://pho-gt-mysql.c1qgi0ayimmy.ap-southeast-2.rds.amazonaws.com:3306/pho_1986_db?createDatabaseIfNotExist=true&useSSL=true&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
    username: ${SPRING_DATASOURCE_USERNAME:pho_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

app:
  cors:
    allowed-origins: ${CLIENT_ORIGIN:http://localhost:5173,http://localhost:3000,http://3.25.130.70,https://pho-gt.vercel.app,https://pho-gt-git-main-hieutran2901s-projects.vercel.app}
  security:
    admin-seed:
      enabled: ${ADMIN_SEED_ENABLED:false}
      phone: ${ADMIN_INIT_PHONE:}
      password: ${ADMIN_INIT_PASSWORD:}
      full-name: ${ADMIN_INIT_NAME:Quản Trị Viên 1986}
      email: ${ADMIN_INIT_EMAIL:admin@pho1986.vn}
